import type { Options } from '#types/index.d.ts';
import type { CoreRules } from '#types/eslintRules.d.ts';
import type { DeepNonNullable } from '#types/helpers.d.ts';

function getJavaScriptRules(options: DeepNonNullable<Options>) {
  const { maxDepth, functionStyle, maxNestedCallbacks, preferNamedExports } = options.configs.base;

  const javascriptRules = {
    /* Possible Problems */
    'array-callback-return': 'error',
    'constructor-super': 'error',
    'for-direction': 'error',
    'getter-return': 'error',
    'no-async-promise-executor': 'error',
    'no-await-in-loop': 'error',
    'no-case-declarations': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': 'error',
    'no-const-assign': 'error',
    'no-constant-binary-expression': 'error',
    'no-constant-condition': 'error',
    'no-constructor-return': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-delete-var': 'error',
    'no-dupe-args': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-else-if': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-duplicate-imports': ['error', {
      includeExports: true,
      allowSeparateTypeImports: true,
    }],
    'no-empty-character-class': 'error',
    'no-empty-pattern': 'error',
    'no-empty-static-block': 'error',
    'no-ex-assign': 'error',
    'no-fallthrough': 'error',
    'no-func-assign': 'error',
    'no-global-assign': 'error',
    'no-import-assign': 'error',
    'no-inner-declarations': 'warn',
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'warn',
    'no-loss-of-precision': 'error',
    'no-misleading-character-class': 'error',
    'no-promise-executor-return': 'error',
    'no-self-compare': 'warn',
    'no-template-curly-in-string': 'error',
    'no-unassigned-vars': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unreachable-loop': 'warn',
    'no-unsafe-negation': ['error', { enforceForOrderingRelations: true }],
    'no-unsafe-optional-chaining': ['error', { disallowArithmeticOperators: true }],
    'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    'no-use-before-define': ['error', {
      functions: false,
      ignoreTypeReferences: false,
    }],
    'no-useless-assignment': 'error',
    'require-atomic-updates': 'warn',
    'use-isnan': ['error', { enforceForIndexOf: true }],
    'valid-typeof': 'error',

    /* Suggestions */
    'accessor-pairs': 'error',
    'block-scoped-var': 'warn',
    'camelcase': ['warn', {
      properties: 'never',
      ignoreImports: true,
      ignoreDestructuring: true,
    }],
    'class-methods-use-this': 'error',
    'complexity': 'warn',
    'consistent-return': 'error',
    'consistent-this': 'error',
    'curly': ['warn', 'multi-line'],
    'default-case': 'warn',
    'default-case-last': 'warn',
    'default-param-last': 'warn',
    'dot-notation': 'warn',
    'eqeqeq': 'error',
    'func-name-matching': 'warn',
    'func-style': ['warn', functionStyle, { allowTypeAnnotation: true }],
    'guard-for-in': 'warn',
    'init-declarations': 'error',
    'logical-assignment-operators': ['error', 'always'],
    'max-depth': ['warn', maxDepth],
    'max-nested-callbacks': ['warn', maxNestedCallbacks],
    'max-params': ['warn', { countVoidThis: true }],
    'new-cap': 'warn',
    'no-array-constructor': 'error',
    'no-bitwise': ['error', { int32Hint: true }],
    'no-caller': 'error',
    'no-console': ['warn', {
      allow: ['info', 'warn', 'error', 'table', 'group', 'groupEnd', 'groupCollapsed'],
    }],
    'no-empty': 'warn',
    'no-empty-function': ['error', {
      allow: [
        'overrideMethods',
        'decoratedFunctions',
        'privateConstructors',
        'protectedConstructors',
      ],
    }],
    'no-eq-null': 'warn',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-boolean-cast': ['error', { enforceForInnerExpressions: true }],
    'no-extra-label': 'error',
    'no-implicit-coercion': 'error',
    'no-implicit-globals': 'error',
    'no-implied-eval': 'error',
    'no-invalid-this': 'error',
    'no-iterator': 'warn',
    'no-label-var': 'error',
    'no-lone-blocks': 'error',
    'no-lonely-if': 'error',
    'no-loop-func': 'warn',
    'no-multi-assign': ['error', { ignoreNonDeclaration: true }],
    'no-multi-str': 'error',
    'no-nested-ternary': 'warn',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-native-nonconstructor': 'error',
    'no-new-wrappers': 'error',
    'no-nonoctal-decimal-escape': 'error',
    'no-obj-calls': 'error',
    'no-object-constructor': 'error',
    'no-octal': 'error',
    'no-octal-escape': 'error',
    'no-param-reassign': 'error',
    'no-plusplus': ['error', { allowForLoopAfterthoughts: true }],
    'no-proto': 'warn',
    'no-prototype-builtins': 'error',
    'no-redeclare': 'off',
    'no-regex-spaces': 'error',
    'no-restricted-exports': [
      preferNamedExports ? 'error' : 'off',
      {
        restrictDefaultExports: {
          named: true,
          namedFrom: true,
          defaultFrom: true,
          namespaceFrom: true,
        },
      },
    ],
    'no-return-assign': ['error', 'always'],
    'no-script-url': 'error',
    'no-self-assign': 'error',
    'no-sequences': ['error', { allowInParentheses: false }],
    'no-setter-return': 'error',
    'no-shadow': ['error', {
      hoist: 'all',
      allow: ['name'],
      builtinGlobals: true,
      ignoreTypeValueShadow: false,
      ignoreFunctionTypeParameterNameValueShadow: false,
    }],
    'no-shadow-restricted-names': ['warn', { reportGlobalThis: true }],
    'no-sparse-arrays': 'error',
    'no-this-before-super': 'error',
    'no-throw-literal': 'error',
    'no-undef': 'error',
    'no-undef-init': 'error',
    'no-unexpected-multiline': 'error',
    'no-unneeded-ternary': 'error',
    'no-unreachable': 'error',
    'no-unsafe-finally': 'error',
    'no-unused-expressions': ['error', {
      allowTernary: true,
      enforceForJSX: true,
      allowShortCircuit: true,
      allowTaggedTemplates: true,
    }],
    'no-unused-labels': 'error',
    'no-unused-private-class-members': 'error',
    'no-useless-backreference': 'error',
    'no-useless-call': 'error',
    'no-useless-catch': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-concat': 'error',
    'no-useless-constructor': 'error',
    'no-useless-escape': 'error',
    'no-useless-rename': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'no-void': 'error',
    'no-with': 'error',
    'object-shorthand': 'warn',
    'operator-assignment': 'error',
    'prefer-arrow-callback': ['warn', { allowUnboundThis: true }],
    'prefer-const': 'error',
    'prefer-destructuring': ['warn', { array: false }],
    'prefer-exponentiation-operator': 'warn',
    'prefer-named-capture-group': 'warn',
    'prefer-numeric-literals': 'warn',
    'prefer-object-has-own': 'warn',
    'prefer-object-spread': 'warn',
    'prefer-promise-reject-errors': ['warn', { allowEmptyReject: true }],
    'prefer-regex-literals': ['warn', { disallowRedundantWrapping: true }],
    'prefer-rest-params': 'warn',
    'prefer-spread': 'warn',
    'prefer-template': 'warn',
    'preserve-caught-error': 'warn',
    'radix': ['error', 'as-needed'],
    'require-await': 'warn',
    'require-yield': 'error',
    'sort-imports': 'off',
    'strict': 'error',
    'symbol-description': 'warn',
    'yoda': 'warn',
  } satisfies CoreRules;

  return javascriptRules;
}

export { getJavaScriptRules };
