import type { PluginRules } from '#types/eslintRules.d.ts';

const unicornRules = {
  'unicorn/better-dom-traversing': 'warn',
  'unicorn/catch-error-name': 'warn',
  'unicorn/consistent-assert': 'warn',
  'unicorn/consistent-compound-words': 'warn',
  'unicorn/consistent-date-clone': 'warn',
  'unicorn/consistent-destructuring': 'warn',
  'unicorn/consistent-empty-array-spread': 'warn',
  'unicorn/consistent-existence-index-check': 'warn',
  'unicorn/consistent-function-scoping': ['warn', { checkArrowFunctions: false }],
  'unicorn/consistent-json-file-read': 'error',
  'unicorn/consistent-template-literal-escape': 'warn',
  'unicorn/custom-error-definition': 'error',
  'unicorn/dom-node-dataset': 'warn',
  'unicorn/empty-brace-spaces': 'warn',
  'unicorn/error-message': 'error',
  'unicorn/escape-case': 'warn',
  'unicorn/explicit-length-check': 'warn',
  'unicorn/isolated-functions': 'error',
  'unicorn/new-for-builtins': 'error',
  'unicorn/no-abusive-eslint-disable': 'error',
  'unicorn/no-accessor-recursion': 'error',
  'unicorn/no-array-callback-reference': 'warn',
  'unicorn/no-array-fill-with-reference-type': 'error',
  'unicorn/no-array-from-fill': 'warn',
  'unicorn/no-array-method-this-argument': 'warn',
  'unicorn/no-await-expression-member': 'warn',
  'unicorn/no-await-in-promise-methods': 'error',
  'unicorn/no-blob-to-file': 'warn',
  'unicorn/no-canvas-to-image': 'warn',
  'unicorn/no-console-spaces': 'warn',
  'unicorn/no-document-cookie': 'warn',
  'unicorn/no-duplicate-set-values': 'error',
  'unicorn/no-exports-in-scripts': 'error',
  'unicorn/no-for-loop': 'warn',
  'unicorn/no-hex-escape': 'warn',
  'unicorn/no-immediate-mutation': 'warn',
  'unicorn/no-incorrect-query-selector': 'error',
  'unicorn/no-invalid-fetch-options': 'error',
  'unicorn/no-invalid-remove-event-listener': 'error',
  'unicorn/no-late-current-target-access': 'warn',
  'unicorn/no-lonely-if': 'warn',
  'unicorn/no-magic-array-flat-depth': 'warn',
  'unicorn/no-negation-in-equality-check': 'warn',
  'unicorn/no-nested-ternary': 'warn',
  'unicorn/no-new-buffer': 'error',
  'unicorn/no-object-as-default-parameter': 'warn',
  // 'unicorn/no-redundant-comparison': 'warn', // Not released yet.
  'unicorn/no-single-promise-in-promise-methods': 'warn',
  'unicorn/no-static-only-class': 'warn',
  'unicorn/no-thenable': 'error',
  'unicorn/no-this-outside-of-class': 'error',
  'unicorn/no-typeof-undefined': 'warn',
  'unicorn/no-unnecessary-array-flat-depth': 'warn',
  'unicorn/no-unnecessary-array-splice-count': 'warn',
  'unicorn/no-unnecessary-nested-ternary': 'warn',
  'unicorn/no-unnecessary-polyfills': 'warn',
  'unicorn/no-unnecessary-slice-end': 'warn',
  'unicorn/no-unreadable-array-destructuring': 'warn',
  'unicorn/no-unreadable-iife': 'warn',
  'unicorn/no-unused-array-method-return': 'warn',
  'unicorn/no-unused-properties': 'warn',
  'unicorn/no-useless-collection-argument': 'warn',
  'unicorn/no-useless-error-capture-stack-trace': 'warn',
  'unicorn/no-useless-fallback-in-spread': 'warn',
  'unicorn/no-useless-iterator-to-array': 'warn',
  'unicorn/no-useless-length-check': 'warn',
  'unicorn/no-useless-promise-resolve-reject': 'warn',
  'unicorn/no-useless-spread': 'warn',
  'unicorn/no-useless-switch-case': 'warn',
  'unicorn/no-useless-undefined': ['warn', { checkArrowFunctionBody: false }],
  'unicorn/no-zero-fractions': 'warn',
  'unicorn/number-literal-case': 'warn',
  'unicorn/numeric-separators-style': 'warn',
  'unicorn/prefer-add-event-listener': 'warn',
  'unicorn/prefer-array-flat': 'warn',
  'unicorn/prefer-array-flat-map': 'warn',
  'unicorn/prefer-array-index-of': 'warn',
  'unicorn/prefer-array-last-methods': 'warn',
  'unicorn/prefer-array-some': 'warn',
  'unicorn/prefer-at': 'warn',
  'unicorn/prefer-bigint-literals': 'warn',
  'unicorn/prefer-blob-reading-methods': 'warn',
  'unicorn/prefer-class-fields': 'warn',
  'unicorn/prefer-classlist-toggle': 'warn',
  'unicorn/prefer-date-now': 'warn',
  'unicorn/prefer-dom-node-append': 'warn',
  'unicorn/prefer-dom-node-remove': 'warn',
  'unicorn/prefer-dom-node-text-content': 'warn',
  'unicorn/prefer-event-target': 'warn',
  'unicorn/prefer-export-from': ['warn', { checkUsedVariables: false }],
  'unicorn/prefer-get-or-insert-computed': 'warn',
  'unicorn/prefer-https': 'warn',
  'unicorn/prefer-import-meta-properties': 'warn',
  'unicorn/prefer-includes': 'warn',
  'unicorn/prefer-iterator-to-array-at-end': 'warn',
  'unicorn/prefer-keyboard-event-key': 'error',
  'unicorn/prefer-logical-operator-over-ternary': 'warn',
  'unicorn/prefer-math-abs': 'warn',
  'unicorn/prefer-math-min-max': 'warn',
  'unicorn/prefer-math-trunc': 'warn',
  'unicorn/prefer-modern-dom-apis': 'warn',
  'unicorn/prefer-modern-math-apis': 'warn',
  'unicorn/prefer-module': 'error',
  // 'unicorn/prefer-native-coercion-functions': 'warn', https://github.com/sindresorhus/eslint-plugin-unicorn/issues/3140
  'unicorn/prefer-negative-index': 'warn',
  'unicorn/prefer-node-protocol': 'warn',
  // 'unicorn/prefer-number-is-safe-integer': 'warn', // Not released yet.
  'unicorn/prefer-number-properties': 'warn',
  'unicorn/prefer-object-from-entries': 'warn',
  'unicorn/prefer-optional-catch-binding': 'warn',
  'unicorn/prefer-queue-microtask': 'warn',
  'unicorn/prefer-reflect-apply': 'warn',
  'unicorn/prefer-regexp-test': 'warn',
  'unicorn/prefer-response-static-json': 'warn',
  'unicorn/prefer-set-size': 'warn',
  'unicorn/prefer-simple-condition-first': 'warn',
  'unicorn/prefer-single-call': 'warn',
  'unicorn/prefer-spread': 'warn',
  'unicorn/prefer-string-match-all': 'warn',
  'unicorn/prefer-string-pad-start-end': 'warn',
  'unicorn/prefer-string-repeat': 'warn',
  'unicorn/prefer-string-replace-all': 'warn',
  'unicorn/prefer-string-slice': 'warn',
  'unicorn/prefer-string-starts-ends-with': 'warn',
  'unicorn/prefer-string-trim-start-end': 'warn',
  'unicorn/prefer-structured-clone': 'warn',
  // 'unicorn/prefer-temporal': 'warn', // Not released yet.
  'unicorn/prefer-top-level-await': 'warn',
  'unicorn/prefer-type-error': 'warn',
  'unicorn/relative-url-style': 'warn',
  'unicorn/require-array-join-separator': 'warn',
  'unicorn/require-module-attributes': 'error',
  'unicorn/require-module-specifiers': 'error',
  'unicorn/require-number-to-fixed-digits-argument': 'warn',
  'unicorn/require-passive-events': 'warn',
  'unicorn/require-post-message-target-origin': 'error',
  'unicorn/switch-case-braces': 'warn',
  'unicorn/switch-case-break-position': 'error',
  'unicorn/template-indent': 'warn',
  'unicorn/text-encoding-identifier-case': 'warn',
  'unicorn/throw-new-error': 'warn',
} satisfies PluginRules<'unicorn'>;

function getUnicornRules() {
  return unicornRules;
}

export { getUnicornRules };
