savePrefix: ''
useBetaCli: true
shellEmulator: true

publicHoistPattern:
  - eslint
  - oxlint

ignoredBuiltDependencies:
  - esbuild
  - unrs-resolver
  - simple-git-hooks

peerDependencyRules:
  allowedVersions:
    eslint-plugin-vue>vue-eslint-parser@^10.0.0: 9.4.3
