name: CI

on: [push, pull_request]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  Validation:
    name: Validate the Code
    runs-on: ubuntu-latest
    steps:
      - name: Prepare the Environment
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install PNPM
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: pnpm
          node-version: node

      - name: Install the Dependencies
        run: pnpm install --ignore-scripts

      - name: Run the Validations
        run: pnpm run ci:validate

      - name: Verify the Documentation is Up to Date
        run: |
          pnpm generate:docs
          if git diff --quiet README.md; then
            echo "✅ Documentation is up to date."
          else
            echo '::error title=Stale Documentation::❌ Documentation is not up to date. Make sure to run `pnpm generate:docs` before committing the changes.'
            exit 1
          fi
