name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Validation:
    name: Validate the code
    runs-on: ubuntu-latest
    steps:
      - name: Prepare the environment
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install PNPM
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: pnpm
          node-version: node

      - name: Install the dependencies
        run: pnpm install --ignore-scripts

      - name: Run the validations
        run: pnpm run ci:validate

      - name: Verify the documentation is up to date
        run: |
          pnpm generate:docs
          if git diff --quiet README.md; then
            echo "::notice::Documentation is up to date."
          else
            echo '::error title=Outdated Documentation::Documentation is not up to date. Run `pnpm generate:docs` before committing the changes.'
            exit 1
          fi
