name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Validation:
    name: Validate the code
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup

      - name: Run the validations
        run: pnpm run ci:validate

      - name: Verify the documentation is up to date
        run: |
          pnpm generate:docs
          if git diff --quiet README.md; then
            echo "::notice::Documentation is up to date."
          else
            echo '::error title=Outdated Documentation::Documentation is not up to date. Run `pnpm generate:docs` before committing the changes.'
            exit 1
          fi
