name: RELEASE

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The type of version-bump (patch, minor, or major)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    name: Release a New Version
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Prepare the Environment
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: node
          registry-url: 'https://registry.npmjs.org'

      - name: Install PNPM
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Install the Dependencies
        run: pnpm install

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Bump the Version & Create a New Tag
        id: version
        run: |
          pnpm version ${{ github.event.inputs.version }} --no-git-tag-version
          clean_version=$(jq -r .version package.json)
          git commit -am "chore: release v$clean_version" --no-verify
          git tag -am "Release v$clean_version" "v$clean_version"
          git push --follow-tags
          echo "tag=v$clean_version" >> $GITHUB_OUTPUT

      - name: Publish to the NPM Registry
        run: pnpm publish --access public --no-git-checks

      - name: Generate a Changelog
        id: changelog
        uses: requarks/changelog-action@b78a3354a01f4a1affb484b9264b506a815c46b1 # v1.10.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version.outputs.tag }}
          writeToFile: false
          useGitmojis: false
          includeRefIssues: true
          includeInvalidCommits: true
          restrictToTypes: feat,perf,fix,docs,refactor

      - name: Create a Draft GitHub Release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          draft: true
          makeLatest: true
          allowUpdates: true
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version.outputs.tag }}
          body: ${{ steps.changelog.outputs.changes }}
